---
title: "Code explanations"
author: "Christoph Schulze"
date: "27 September 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 0 - R setup
First of all, make sure you installed the *qmethod* package by Aiora Zabala. 
```r
install.packages("qmethod")
```

In the beginning of your document, make sure to **call** the library.

```r
library(qmethod)
```
Next up, set the according working directory

```r
setwd("your_directory")
```

# 1 - Loading data into R

So, an important note before importing the data (in that case here called **q_data.csv**), delete in excel first column and save as csv file. Optionally, you can save the data then in a separate file.

```r
qdata <- read.csv("q_data.csv", header=TRUE, sep=";",dec=".")

save(qdata,file = "qdata.RData")
```

# 2 - Very basic analysis

Just to get a first idea of your data, having a quick look at the correlations

```r
cor(qdata)
```

# 3 - Q analysis

At this stage we will tell R: "Have a look at he data and check for 3 Factors". This is very crucial here. From now on we will use the features of the *qmethod* package.\
The *qmethod* function below goes throw our data. Based on statistical criteria mentioned further on we will have to decide if we are ok with the number of factors, or if we have to decrease the number further.

```r
results <- qmethod(qdata, nfactors = 3)
```

# 4 - Extracting factors

Watts and Stenner (2012) provide a good overview of Q-methodology and the respective criteria that determine the number of extracted factors.
```r
results$flag

loa.and.flags(results)
```
Among one of these criteria is the number of Q-sorts belonging to a factor. The commands above return the Q-sorts which significantly load onto a certain factor. This significantly loading onto a factor is called "Flagging". Each Q-sort can only load onto one factor. However, it might occur that one Q-sort may load relatively high on multiple factors. In that case, we cannot clearly attribute the person's Q-sort to one sinle factor, leading to a potential exclusion of that Q-sort. As stated by Zabala (2014), there are two relevant criteria for flagging a Q-sort:

 * 1) qsorts which factor loading is higher than the threshold for pval >0.95, and 
 * 2) qsorts which square loading is higher than the sum of square loadings of the same q-sort in all other factors

```r
results$f_char$characteristics
```
Other criteria can be found in the table above. Based on Watts and Stenner (2012), the following criteria play a role in determining the number of factors extracted from the analysis:

  * minimum number of Q-sorts $\geq$ 2
  * Eigenvalue $\geq$ 1
  * share of accumulated explained variance of extracted factors $\geq$ 30%
  * Humphreys rule
  * Screeplot

Humphreys rule basically states that the product of the two highest factor loadings must exceed $\frac{-2}{\sqrt{n}}$
```r
humphrey<-2/sqrt(dim(qstake))
humphrey
```

The last criteria is a graphical description of variance explained by additional factors. Here, a kink in the line should indicate a cut-off point of additional factors.

```r
screeplot(prcomp(qstake), main = "Screeplot of unrotated factors", type = "l")
```
# 5 - Making sense of the extracted factors

```r
summary(results)
results
```

Comparing z-scores
```r
plot(results)
```


```r
scores <- cbind(round(results$zsc, digits=2), results$zsc_n) 
nfactors <- ncol(results$zsc) 
col.order <- as.vector(rbind(1:nfactors, (1:nfactors)+nfactors)) 
scores <- scores[col.order] 
scores
```

```r
scores[order(scores$zsc_f1, decreasing = T), ]

scores[order(scores$zsc_f2, decreasing = T), ] 
scores[order(scores$zsc_f3, decreasing = T), ]
scores[order(scores$zsc_f4, decreasing = T), ] 
scores[order(scores$zsc_f5, decreasing = T), ]
```


```r
results$qdc

results$qdc[which(results$qdc$dist.and.cons == "Consensus"), ]

results$qdc[which(results$qdc$dist.and.cons == "Distinguishes all"), ]

results$qdc[which(results$qdc$dist.and.cons == "Distinguishes f1 only"), ]

results$qdc[which(results$qdc$dist.and.cons == "Distinguishes f2 only"), ]

results$qdc[which(results$qdc$dist.and.cons == "Distinguishes f3 only"), ]

results$qdc[which(results$qdc$dist.and.cons == "Distinguishes f4 only"), ]

results$qdc[which(results$qdc$dist.and.cons == "Distinguishes f5 only"), ]
```

# 6 - Saving results
```r
save(results, file = "practiseresults.Rdata")

# Table of z-scores: 
write.csv(results$zsc, file = "zscores.csv") 

# Table of factor scores: 
write.csv(results$zsc_n, file = "factorscores.csv") 

# Table of Q-sort factor loadings: 
write.csv(results$loa, file = "loadings.csv")
```

```r
export.qm(results, file = "myreport.txt", style = "R")

export.qm(results, file = "myreport-pqm.txt", style = "PQMethod")
```
# References

Watts, S., & Stenner, P. (2012). Doing Q methodological research: Theory, method & interpretation. Sage.\
Zabala, A. (2014). qmethod: A package to explore human perspectives using Q methodology.
